### PR TITLE
#164798187 User Should view their reading stats

### PR DESCRIPTION
**Pull request by ezrogha**
#### What does this PR do?
Enable user to view their most recently viewed articles

#### Description of Task to be completed?
- Allow a user to view their reading stats

#### How should this be manually tested?
- Fetch this branch git fetch origin `users-should-see-their-reading-stats-164798187`
- Checkout to the branch git checkout `users-should-see-their-reading-stats-164798187`
- Run npm start to view the landing page
- Login to the app on `/Login`
- click `Check the Articles Reading Stats`

#### What are the relevant pivotal tracker stories?
[#164798187](https://www.pivotaltracker.com/story/show/164798187)

#### Screenshots (if appropriate)
Screenshot 2019-05-24 at 11 16 39

Screenshot 2019-05-23 at 22 00 25

### CODE REVIEW

**Review by hadijahkyampeire — APPROVED** [review]
Great work but it will be more helpful to add a link on the dashboard which a user can click to see the reading stats, it is not user-friendly to expect someone to just type a URL, how will they know it

**Comment by hadijahkyampeire** [comment]
Just go into the `dashboard` component and add a link
`<Link to="/reading-stats">`[Check the Articles Reading Stats](http:localhost:8080/reading-stats)`</Link>` 
give it an appropriate color and that's all, however, the test for the dashboard might require to be wrapper in `MemoryRouter`, ensure you run tests before you push. Incase `MemoryRouter` make some assertions fail, let me know or change `<Link>` to `<a>, but for internal links `<Link>` is preffered.

**Comment by ezrogha** [comment]
> Great work but it will be more helpful to add a link on the dashboard which a user can click to see the reading stats, it is not user-friendly to expect someone to just type a URL, how will they know it

Thanks for that keen observation @hadijahkyampeire,
I have implemented your feedback

**Comment by ezrogha** [comment]
> Just go into the `dashboard` component and add a link
> `<Link to="/reading-stats">`[Check the Articles Reading Stats](http:localhost:8080/reading-stats)`</Link>`
> give it an appropriate color and that's all, however, the test for the dashboard might require to be wrapper in `MemoryRouter`, ensure you run tests before you push. Incase `MemoryRouter` make some assertions fail, let me know or change `<Link>` to `<a>, but for internal links `` is preffered.

I have tried using `<Link />` which moved to the page but didn't load any content, I have now opted `<a>`

**Review by felixkiryowa — APPROVED** [review]
Good work

**Pull request merged**
